export type PageType = 'pricing' | 'features' | 'homepage' | 'blog' | 'careers';

export type Momentum = 'rising' | 'stable' | 'slowing' | 'declining' | 'insufficient-data';

export type ThreatLevel = 'critical' | 'high' | 'medium' | 'low' | 'monitor';

export type PredictedMoveCategory =
  | 'product'
  | 'pricing'
  | 'funding'
  | 'hiring'
  | 'geo'
  | 'strategic';

export type PredictedMoveTimeHorizon = '30d' | '60d' | '90d';

export interface PredictedMove {
  move: string;
  reasoning: string;
  probability: number;
  timeHorizon: PredictedMoveTimeHorizon;
  category: PredictedMoveCategory;
}

export type PredictionStatus =
  | 'pending'
  | 'realized'
  | 'partially-realized'
  | 'expired';

/**
 * A prediction that has been (or is awaiting) evaluation against subsequent
 * research. Stored in `Competitor.predictionHistory` for track-record display.
 */
export interface EvaluatedPrediction {
  move: string;
  reasoning: string;
  probability: number;
  timeHorizon: PredictedMoveTimeHorizon;
  category: PredictedMoveCategory;
  predictedAt: string;          // ISO — when originally predicted
  evaluatedAt: string;          // ISO — when this evaluation ran
  status: PredictionStatus;
  evidence?: string;             // 1-2 sentences explaining realization (or null when pending)
  evidenceUrl?: string;          // citation source URL
}

// Win-against tactics (Phase 21) — concrete sales-enablement moves the user's
// team can take to compete vs this competitor, generated by Haiku from the
// user's company context + the competitor's derivedState. Cached on the
// Competitor record keyed by latestResearchId; invalidates on next research.
export type WinAgainstDifficulty = 'easy' | 'moderate' | 'hard';
export type WinAgainstImpact = 'low' | 'medium' | 'high';

export interface WinAgainstTactic {
  /** 1-sentence imperative — e.g. "Lead pricing conversations with our annual discount." */
  tactic: string;
  /** 1-2 sentence rationale tied to the competitor's state. */
  reasoning: string;
  difficulty: WinAgainstDifficulty;
  impact: WinAgainstImpact;
}

export interface Competitor {
  id: string;
  userId: string;
  name: string;
  url: string;
  pagesToTrack: PageType[];
  status: 'active' | 'paused';
  createdAt: string;
  updatedAt: string;
  momentum?: Momentum;
  momentumChangePercent?: number;
  momentumAsOf?: string;
  threatLevel?: ThreatLevel;
  threatReasoning?: string;
  threatAsOf?: string;
  derivedTags?: string[];
  derivedTagsAsOf?: string;
  predictedMoves?: PredictedMove[];
  predictedMovesAsOf?: string;
  predictionHistory?: EvaluatedPrediction[];
  predictionHistoryAsOf?: string;

  // Win-against tactics cache (Phase 21). Lazily populated by the
  // `POST /competitors/{id}/battlecard` handler — only paid for when the
  // user actually generates a battlecard. `winAgainstTacticsResearchId`
  // is the cache-key: when the latest ResearchFinding's id no longer
  // matches, regenerate.
  winAgainstTactics?: WinAgainstTactic[];
  winAgainstTacticsAsOf?: string;
  winAgainstTacticsResearchId?: string;

  // Recurring research cadence (Phase 1). `researchCadenceDays` overrides the
  // tier-level default from PLAN_LIMITS.researchCadenceDaysDefault. Null/absent
  // means use the tier default. `lastRecurringResearchAt` is set by the
  // recurring-research enqueuer Lambda after each scheduled run, used to skip
  // competitors whose latest run is still fresh.
  researchCadenceDays?: number;
  lastRecurringResearchAt?: string;

  // Snooze (Phase 7a). When set + in the future, the competitor is fully
  // silenced: recurring research skips it, aggregate-changes filters out
  // its changes from the weekly digest, real-time critical alerts are
  // suppressed, and the dashboard hides changes from this competitor by
  // default. Auto-expires at `snoozedUntil`. Set to null/undefined to
  // un-snooze. `snoozedAt` records when the snooze started for forensic
  // logging + a future "snooze history" view.
  snoozedUntil?: string;
  snoozedAt?: string;
}
