import { DraftBanner } from "@/components/shared/draft-banner";

export const metadata = {
  title: "Terms of Service — RivalScan",
};

export default function TermsPage() {
  return (
    <>
      <h1>Terms of Service</h1>
      <p className="text-xs text-muted-foreground">Last updated: 2026-04-30</p>

      <DraftBanner kind="agreement" />

      <h2>1. Acceptance</h2>
      <p>
        By creating an account or using RivalScan, you agree to these Terms,
        our <a href="/legal/privacy">Privacy Policy</a>, and our{" "}
        <a href="/legal/aup">Acceptable Use Policy</a> (collectively, the
        &quot;Agreement&quot;). If you do not agree, do not use the service.
      </p>

      <h2>2. The service</h2>
      <p>
        RivalScan is an AI-powered competitive intelligence service. We
        research publicly available information about competitor businesses
        you specify and present analyses, predictions, and summaries via the
        dashboard and weekly digest emails.
      </p>

      <h2>3. Account &amp; eligibility</h2>
      <p>
        You must be at least 18 years old and use the service for legitimate
        business purposes. You are responsible for the security of your
        account credentials and for all activity under your account.
      </p>

      <h2>4. Acceptable use</h2>
      <p>
        Your use of RivalScan is governed by our{" "}
        <a href="/legal/aup">Acceptable Use Policy</a>, which prohibits
        researching individuals (rather than businesses), sanctioned entities,
        and other misuse cases. Violations may result in immediate suspension
        and may be reported to law enforcement.
      </p>

      <h2>5. AI-generated content disclaimer</h2>
      <p>
        Outputs from RivalScan — including research summaries, change
        analyses, threat assessments, predictions, and weekly digests — are
        generated by large language models and may contain errors,
        inaccuracies, or outdated information. <strong>Do not rely on
        RivalScan output as legal, financial, investment, or trading advice.</strong>{" "}
        Independently verify any material claim before acting on it. RivalScan
        is not registered as an investment advisor.
      </p>

      <h2>6. Subscriptions, billing, refunds</h2>
      <p>
        Subscriptions are billed monthly or annually via Paddle, our merchant
        of record. Cancel anytime via your account settings or the Paddle
        customer portal; access continues through the end of the current
        billing period. Refunds are at our discretion except where required by
        consumer-protection law in your jurisdiction.
      </p>

      <h2>7. Intellectual property</h2>
      <p>
        We retain all rights to the RivalScan platform. You retain ownership
        of the data you input. We grant you a limited license to use the
        outputs for internal evaluation. You may not redistribute, republish,
        or commercialize RivalScan-generated text without our written
        permission.
      </p>

      <h2>8. Confidentiality</h2>
      <p>
        We treat the list of competitors you track and the contents of your
        dashboard as confidential to your account. We will not share this
        information with other customers.
      </p>

      <h2>9. Termination</h2>
      <p>
        Either party may terminate at any time. Upon termination, your data
        is erased per Section 7 of the Privacy Policy. We may suspend
        accounts immediately for AUP violations.
      </p>

      <h2>10. Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, RivalScan&apos;s aggregate
        liability is limited to the amount you paid in the 12 months preceding
        the claim. We are not liable for indirect, consequential, or
        speculative damages.
      </p>

      <h2>11. Indemnity</h2>
      <p>
        You agree to indemnify us against claims arising from your misuse of
        the service, your AUP violations, or your redistribution of outputs
        in violation of Section 7.
      </p>

      <h2>12. Governing law &amp; disputes</h2>
      <p>
        This Agreement is governed by [JURISDICTION]. Disputes are resolved by
        binding arbitration except for injunctive relief.
      </p>

      <h2>13. Changes</h2>
      <p>
        We may modify these Terms; material changes will be communicated by
        email at least 14 days before they take effect. Continued use after
        the effective date constitutes acceptance.
      </p>

      <h2>14. Contact</h2>
      <p>
        Questions: <a href="mailto:legal@rivalscan.com">legal@rivalscan.com</a>.
      </p>
    </>
  );
}
